### ISSUE TITLE
Could you add some stuff to make it look more like this...

### ISSUE THREAD

**Issue by engineswap** [momothereal/java-canary-webhooks#2]
![image](https://user-images.githubusercontent.com/38859788/41890518-77c6530e-78d5-11e8-81a6-76516c8d8345.png)

**Comment by aramperes** [comment]
This is done using [embeds](https://github.com/momothereal/java-canary-webhooks/blob/master/src/main/java/ca/momoperes/canarywebhooks/embed/DiscordEmbed.java).

**Comment by engineswap** [comment]
Well I can't get the IMG to work in any way, ive tried links and saving it but I don't know how to upload a IMG, can you help?
